### ISSUE TITLE
React Modal Warning

### ISSUE THREAD

**Issue by gurusewak** [DimitryDushkin/sliding-pane#7]
I am getting the following warning in my console during the slide animation 

Warning: react-modal: App element is not defined. Please use `Modal.setAppElement(el)` or set `appElement={el}`. This is needed so screen readers don't see main content when modal is opened. It is not recommended, but you can opt-out by setting `ariaHideApp={false}`.

Can you please help me resolving this. Thanks in advance! @DimitryDushkin

**Comment by DimitryDushkin** [comment]
Thank you for finding this.
I've modified example to eliminate the warning — https://github.com/DimitryDushkin/sliding-pane/blob/master/docs/src/app.js#L18-L20

Because SlidingPane can be really deep in VDOM I believe the best way to handle this warning is to use `Modal.setAppElement` in top component.

**Comment by gcardacci** [comment]
I had the same error and I could correct it using Modal.setAppElement. But that function should be in the main file of the project (app.js in this case) or in each particular file in which sliding pane is used?

**Comment by shri-msk-2018-reviewer** [comment]
@gcardacci just once in app.js.
